/*
 Generated by typeshare 1.11.0
*/

export interface NewUser {
  name: string;
  titles: string[];
}

export interface User {
  id: number;
  name: string;
  titles: string[];
}

export interface UserId {
  id: number;
}

export interface UserShowProps {
  users: User[];
}

export interface Users {}
