/*
 Generated by typeshare 1.11.0
*/

/** Add vector so we can use proper form dependency */
export interface User {
	id: number;
	name: string;
	titles: string[];
}

export interface UserShowProps {
	users: User[];
}

