[[language]]
name = "typescript"
formatter = { command = "pnpm", args = ["-C", "web-client", "exec", "prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "svelte"
auto-format = true
